{
 "title": "Mev Relay",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Beacon",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Proposal slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chain_state_slot",
     "query": "SELECT * FROM \"beacon_proposal_slot\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Block",
     "query": "SELECT * FROM \"beacon_block\""
    },
    {
     "alias": "Consensus validators",
     "query": "SELECT * FROM \"relay_known_validators\" "
    }
   ]
  },
  {
   "title": "Relay",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Validators",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chain_state_slot",
     "query": "SELECT * FROM \"relay_registered_validators\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "$B / $C * 100", "type": "math" },
    {
     "alias": "Blocks",
     "query": "SELECT * FROM \"relay_relayed_blocks\""
    },
    { "expression": "$D/ $E * 100", "type": "math" }
   ]
  },
  {
   "title": "Block Txs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "Tx count",
     "query": "SELECT mean(\"gauge\") FROM \"relay_tx_count\" WHERE $timeFilter GROUP BY time(1m)"
    }
   ]
  },
  {
   "title": "Block value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expression": "$A / 1e18", "type": "math" }
   ]
  },
  {
   "title": "Latency MS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "Headers",
     "query": "SELECT mean(\"gauge\") FROM \"relay_header_latency\" WHERE $timeFilter GROUP BY time(1m)"
    },
    {
     "alias": "Blocks",
     "query": "SELECT mean(\"gauge\") FROM \"relay_blinded_block_latency\" WHERE $timeFilter GROUP BY time(1m)"
    }
   ]
  }
 ]
}